Implement basic auth handling
Apicurio/apicurio-common-ui-components pull request #89
Opened 2024-05-03 14:47 UTC by andreaTP

Depends on:
https://github.com/Apicurio/apicurio-common-app-components/pull/155

2024-05-06 14:32 UTC, EricWittmann commented on lib/auth/ApplicationAuth.tsx
> +                </Modal>
Can you make this a standalone component rather than having it inline?

2024-05-06 14:33 UTC, EricWittmann requested changes
Just one request before merging.

2024-05-06 16:22 UTC, andreaTP commented on lib/auth/ApplicationAuth.tsx
> +                </Modal>
sure, make sense, done :slightly_smiling_face:

2024-05-08 10:10 UTC, andreaTP commented
@EricWittmann ready for another review round!

2024-05-08 14:02 UTC, EricWittmann requested changes
I'm not seeing what these wrapper types are doing for you.

2024-05-08 14:02 UTC, EricWittmann commented on lib/auth/ApplicationAuth.tsx
> +}
Why the wrapper?

2024-05-08 14:11 UTC, EricWittmann approved these changes
LGTM

2024-05-08 14:11 UTC, merged